#! /bin/bash
TMP=$(getopt -o U::u:p: --long user: -- "$@")
eval set -- "$TMP"
while true
do
	case "$1" in
		-u)
			user=$2; shift 2 ;;
		-U)
			user=root
			shift 2;;
		-p)
			dir=$2 
			shift 2;;
		--)
			shift
			break;;
		*)
			exit 1;;
	esac
done
ip_list=$(ip a | grep "inet " | awk '{print $2}' | cut -d'/'  -f1)
scp_cmd=scp
: ${user:=$USER}
: ${dir:=$PWD}
(id -u "$user") > /dev/null 2>&1
if [ ! $? -eq 0 ]
then
	echo invalid user
	exit 1
fi
if [ ${dir:0:1} != '/' ]
then
	dir=${PWD%/}/$dir
fi

for ip in $ip_list
do
	if [ $ip == "127.0.0.1" ]
	then
		continue
	fi
	if [ "$*" == "" ]
	then
		echo $scp_cmd $user@$ip:$dir .
		exit
	fi
	for target in "$@"
	do
		echo $scp_cmd $user@$ip:$dir/$target .
	done
done
