#!/bin/bash

#sle 15 on ha-2
echo 000000000000
no=$1
#((no -- ))
echo $no
host_list=(10.67.162.87
	10.67.162.188
	10.67.162.214)
host=${host_list[$no]}
echo $host
if [ -z $host ]
then
	echo invalid host
fi
echo $host
user=root
passwd=suse
known_hosts="$HOME/.ssh/known_hosts"

if [ -z "$(grep $host ${known_hosts})" ]
then
	echo not known
	ssh -X ${user}@${host}
else
	sshpass -p $passwd ssh -X $user@$host
fi
